# Generated by Django 6.1 on 2026-08-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('question_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='published', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='bcs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_images', models.TextField(blank=True, null=True)),
                ('option_a_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_a_image', models.TextField(blank=True, null=True)),
                ('option_b_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_b_image', models.TextField(blank=True, null=True)),
                ('option_c_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_c_image', models.TextField(blank=True, null=True)),
                ('option_d_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d_image', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=10)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanation_images', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bcs.exam')),
            ],
        ),
    ]
